settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: server
  path: ./cmd/server
  commands:
    run:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - ../../
    ignored_paths:
    - .git
    - .realize
    - vendor
